[project]
name = "biorepository-data-wrangling2"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=2.0.0a0",
    "pandas>=2.3.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
